# loom.R
#

#'
#'@description Add the regulons with their target genes generated by SCENIC as a row attribute to the given .loom handler.
#'@param loom     The loom file handler.
#'@param dgem     A matrix of the gene expression with M genes as rows and N cells as columns.
#'@param regulons A list of list of the regulons and their target genes generated by SCENIC.
#'
add_scenic_regulons<-function(loom
                              , dgem
                              , regulons) {
  regulons.mask<-do.call(what = "cbind", args = lapply(seq_along(regulons), function(regulon.idx) {
    reg.name<-names(regulons)[regulon.idx]
    reg.genes<-regulons[regulon.idx]
    reg.mask<-data.frame("x"=row.names(dgem)%in%reg.genes, stringsAsFactors = F)
    colnames(reg.mask)<-reg.name
    return (reg.mask)
  }))
  row.names(reg.mask)<-row.names(dgem)
  colnames(reg.mask)<-gsub(pattern = " ", replacement = "_", x = colnames(reg.mask))
  add_row_attr(loom = loom, key = "Regulons", value = as.data.frame(x = regulons.mask))
}

#'
#'@description Add the regulons AUC matrix generated by SCENIC as a column attribute to the given .loom handler.
#'@param loom         The loom file handler.
#'@param regulons.AUC A matrix of the regulons AUC values with M regulons as rows and N cells as columns
#'
add_scenic_regulons_auc_matrix<-function(loom
                                         , regulons.AUC) {
  add_col_attr(loom = loom, key = "RegulonsAUC", value = as.data.frame(x = t(regulons.AUC)))
}


#'
#'@description Add the Flybase gene as a row attribute to the given .loom handler.
#'@param loom                       The loom file handler.
#'@param dgem                       A matrix of the gene expression with M genes as rows and N cells as columns.
#'@param fbgn.gn.mapping.file.path  A N-by-2 data.frame containing the mapping between the Flybase gene and the gene symbol.
#'
add_fbgn<-function(loom
                   , dgem
                   , fbgn.gn.mapping.file.path) {
  fbgn.gn.mapping<-read.table(file = fbgn.gn.mapping.file.path, header = F, sep = "\t", quote = '', stringsAsFactors = F)
  colnames(fbgn.gn.mapping)<-c("FBgn","Gene")
  genes<-merge(x = data.frame("Gene"=row.names(dgem)), y = fbgn.gn.mapping, by = "Gene")
  add_row_attr(loom = loom, key = "FBgn", value = genes$FBgn)
}

# Generic functions

#'
#'@description Add a new row attribute to the given .loom object accessible by the given key and containing the given value.
#'@param loom   The loom file handler.
#'@param key    The name for the new added attribute
#'@param value  The value for the new added attribute
#'
add_row_attr<-function(loom
                       , key
                       , value) {
  grp.row.attrs<-loom[["row_attrs"]]
  grp.row.attrs[[key]]<-value
  loom$flush()
}

#'
#'@description Add a new column attribute to the given .loom object accessible by the given key and containing the given value.
#'@param loom   The loom file handler.
#'@param key    The name for the new added attribute
#'@param value  The value for the new added attribute
#'
add_col_attr<-function(loom
                       , key
                       , value) {
  grp.col.attrs<-loom[["col_attrs"]]
  grp.col.attrs[[key]]<-value
  loom$flush()
}

#'
#'@description Add the given gene expression matrix dgem to the given .loom object
#'@param loom The loom file handler.
#'@param dgem A matrix of the gene expression with M genes as rows and N cells as columns.
#'
add_matrix<-function(loom
                     , dgem) {
  row.names(dgem)<-NULL
  colnames(dgem)<-NULL
  loom[["matrix"]]<-t(dgem)
  loom$flush()
}

#'
#'@description
#'@loom The loom file handler.
#'
finalize<-function(loom) {
  loom$flush()
  loom$close_all()
}

#'
#'@param file.name                  A string naming the .loom file to be generated.
#'@param dgem                       A matrix of the gene expression with M genes as rows and N cells as columns.
#'@param default.embedding          A M-by-2 data.frame of the embedding (X and Y coordinates) of the cells.
#'@param fbgn.gn.mapping.file.path  A N-by-2 data.frame containing the mapping between the Flybase gene and the gene symbol.
#'
build_loom<-function(file.name
                     , dgem
                     , default.embedding
                     , fbgn.gn.mapping.file.path) {
  loom<-H5File$new(filename = file.name, mode = "w")
  cn<-colnames(dgem)
  rn<-row.names(dgem)
  # matrix
  print("Adding matrix...")
  add_matrix(loom = loom, dgem = t(dgem))
  # col_attrs
  print("Adding column attributes...")
  loom$create_group("col_attrs")
  add_col_attr(loom = loom, key = "CellID", value = as.character(cn))
  add_col_attr(loom = loom, key = "Embedding", value = as.data.frame(embedding))
  # row_attrs
  print("Adding row attributes...")
  loom$create_group("row_attrs")
  add_row_attr(loom = loom, key = "Gene", value = as.character(rn))
  add_fbgn(loom = loom, dgem = dgem, fbgn.gn.mapping.file.path = fbgn.gn.mapping.file.path)
  # col_edges
  print("Adding columns edges...")
  col.edges<-loom$create_group("col_edges")
  # row_edges
  print("Adding row edges...")
  row.edges<-loom$create_group("row_edges")
  # layers
  print("Adding layers...")
  layers<-loom$create_group("layers")
  loom$flush()
}
